services:
  - type: web
    name: bias-ai-convo-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    runtime: python
    pythonVersion: 3.10.13
